version: 2.1
orbs:
  bazelisk-orb: promiseofcake/bazelisk-orb@0.3.0
  aws-ecr: circleci/aws-ecr@6.15.2
jobs:
  build-and-test:
    docker: 
      - image: circleci/openjdk:9.0.4-sid
    resource_class: xlarge
    steps:
      - checkout
      - run: sudo apt-get update 
      - run: sudo apt-get install gcc g++ python3
      - bazelisk-orb/install
      - run: /home/circleci/.local/bin/bazel test //... 
  push_images: 
    machine: 
      - image: ubuntu-1604:202007-01
    resource_class: xlarge
    steps: 
      - checkout
      - aws-ecr/ecr-login
      - run: sudo apt-get update 
      - run: sudo apt-get install gcc g++ python3 default-jdk
      - bazelisk-orb/install
      - run: ci/push_modified_services.sh    

workflows:
  version: 2.1
  build: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build-and-test
      - push_images:
          requires:
            - build-and-test
          filters:
            branches: 
              only: main
