version: 2.1
orbs:
  bazelisk-orb: promiseofcake/bazelisk-orb@0.3.0
jobs:
  prepare:
    docker: 
      - image: circleci/openjdk:9.0.4-sid
    resource_class: xlarge
    steps:
      - checkout
      - run: sudo apt-get update 
      - run: sudo apt-get install gcc g++ python3
      - run: printenv
      - run: ls /usr/bin/
      - bazelisk-orb/install
  build-and-test: 
    docker: 
      - image: circleci/openjdk:9.0.4-sid
    resource_class: medium
    steps: 
      - checkout
      - run: /home/circleci/.local/bin/bazel test //... 
  push_images: 
    docker: 
      - image: circleci/openjdk:9.0.4-sid
    resource_class: medium
    steps: 
      - run: ci/get_modified_services
workflows:
  version: 2
  build: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - prepare
      - build-and-test:
          requires: 
            - prepare 
      - push_images:
          requires:
            - build-and-test
          filters:
            branches: 
              only: main
