version: 2.1
orbs:
  bazelisk-orb: promiseofcake/bazelisk-orb@0.3.0
jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/node:10.14.0
    steps:
      - checkout
      - bazelisk-orb/install
      - run: bazel build //...
workflows:
  version: 2
  build: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - test
