<<<<<<< Updated upstream
jobs:
  build:
    steps:
      - checkout
      - bazelisk-orb/install
orbs:
  jq: promiseofcake/bazelisk-orb@0.2
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build
=======
version: 2.1
 jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: bazel build //...
 workflows:
   version: 2
   build: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - test
>>>>>>> Stashed changes
