version: 2.1
orbs:
  bazelisk-orb: promiseofcake/bazelisk-orb@0.3.0
  aws-ecr: circleci/aws-ecr@6.15.2
jobs:
  build-and-test:
    docker: 
      - image: circleci/openjdk:9.0.4-sid
    resource_class: xlarge
    steps:
      - checkout
      - run: sudo apt-get update 
      - run: sudo apt-get install gcc g++ python3
      - run: printenv
      - run: ls /usr/bin/
      - bazelisk-orb/install
      - run: /home/circleci/.local/bin/bazel test //... 
      - run: ci/check_service_config_services.sh
  push_images: 
    docker: 
      - image: circleci/openjdk:9.0.4-sid
    resource_class: xlarge
    steps: 
      - checkout
      - run: sudo apt-get update 
      - run: sudo apt-get install gcc g++ python3
      - run: printenv
      - run: ls /usr/bin/
      - bazelisk-orb/install
      - run: ci/push_modified_services.sh    
  authenticate:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - aws-ecr/ecr-login

workflows:
  version: 2.1
  build: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build-and-test
      - authenticate:
          requires:
            - build-and-test
      - push_images:
          requires:
            - authenticate
          filters:
            branches: 
              only: main
