version: 2.1
orbs:
  bazelisk-orb: promiseofcake/bazelisk-orb@0.3.0
jobs:
  build-and-test:
    docker: 
      - image: circleci/openjdk:9.0.4-sid
    resource_class: xlarge
    pre-steps:
      - run: sudo apt-get update 
      - run: sudo apt-get install gcc g++ python3
      - bazelisk-orb/install
    steps:
      - checkout
      - run: /home/circleci/.local/bin/bazel test //... 
workflows:
  version: 2
  build: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build-and-test
