version: 2.1
orbs:
  bazelisk-orb: promiseofcake/bazelisk-orb@0.3.0
jobs:
  test:
    docker: 
      - image: circleci/openjdk:9.0.4-sid
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run: sudo apt-get install gcc
      - run: printenv
      - run: ls /usr/bin/
      - bazelisk-orb/install
      - run: /home/circleci/.local/bin/bazel build --verbose_failures //...
workflows:
  version: 2
  build: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - test
